### ISSUE TITLE
Random blinking leds xbian

### ISSUE THREAD

**Issue by evgsd** [tvdzwan/hyperion#214]
Hi. I am install xbian and configure hyperion. Sometimes i get random color blinking. In previous installed raspbmc all works perfect.

PRi B+
LEDS: ws2801
XBian: 1.0 RC3

**Comment by gavinbenda** [comment]
I have this issue too - it worked fine the first time I set it up (over a year ago) but somewhere since then (the hardware setup hasn't changed) it's not flickering everywhere.
Running an effect or solid colour directly works fine, and if there's a fairly solid colour on the video it seems to work okay, but as soon as there's movement or lots of colour, the LED's randomly flicker, quite violently.

Running raspbmc 3.12.21, latest Hyperion build and using 50x WS2801 LED's connected directly to the GPIO ports and running a separate power supply.

Any thing I can try so I can narrow it down further?

**Comment by Fire69** [comment]
Try lowering the rate in the hyperion.config.json-file.  I have huge random flickering, Lightberry even sent me new hardware, didn't solve the problem.
I lowered the rate to 250000, solved the problem.

**Comment by gren2del** [comment]
I am pretty new to this (completed my LED setup last weekend).  
I am running OpenELEC with Hyperion and I am getting a lot of noise output on the LEDs (random color flashing).  
SD material are not as much influenced as HD material. Still it would be nice to solve the problem.  
I am running a 50 pcs. string of WS2801 LED using RPi B+, with separate DC power adapters for RPI and the LED string.  
I have the Baudrate set to 250000 and the problem still occurs.  

I will try to exchange the cables between the string and the RPi.

**Comment by lobocobra** [comment]
It has probably to do with unshielded cables. You can use either Cat5 Network cable or other shielded cable. I use 100LED with the latest wheezy and latest upgrades with 5 amper power supply and have absolutely no flickering. 
On your case I would start at 0 means.
1) get strong power supply that delivers 1.5 amper per m/LED + 1 ampere for arduino
2) use shielded cables
3) use the same power supply for arduino and LED, ensure that the LED power enters the stripe at the beginning and the end of the stripe
4) use an USB hub with power supply to connet easyCAP (and mouse and keyboard), the HDMI2AV does for me not need any additional power supply (HDMI delivers power)
5) install the latest Hyperion
=> test it with hyperion-remote -c white
If there is not flickering with that setting, your HW is ok.

**Comment by mansp** [comment]
Same issue here when I changed to RPi 2. Previously I had it working on a RPi B with firmware from  May 2014, kernel 3.12 something I believe, and now I use 3.18.7 since thats what xbian for RPi 2 use. 
What I have found it is related to some GPIO implementation, would be nice to have some devs confirm this. I have written a bit about what information I have collected in this thread https://github.com/tvdzwan/hyperion/issues/251. But unfortunately I am not skilled enough to do anything about it. 

M

**Comment by aaronsutton** [comment]
I'm having this very issue with the RPi2 and had the same one with the the RPiB. I'll try the above troubleshooting steps and post back, but for reference, I followed the instructions here: https://github.com/OpenELEC/OpenELEC.tv/issues/3503, and have compiled OpenELEC with the hardware frame scaling patch against kernel 3.19. Could someone post or link me to a working hyperion.config.json file for OpenELEC 5.0.x and an STK1160 capture card?

**Comment by gren2del** [comment]
I have a separate 5V/2A power adapter for RPi B+ and 2V/5A for the LED (more than enough). I have changed the cables to: 
LAN - shielded Cat 5
MicroUSB (power) - shielded 
HDMI - shielded. 
Unfortunately the problem is still there. 
I have tried to play with the Baud Rate settings in Hyperion. The 1.000.000 gives the least flickers. 
What I have also noticed is that there is visible less flickering when playing SD material, rather than HD. 
I have read somewhere that the problem can be Os kernel related.

**Comment by gren2del** [comment]
I have made a mistake: the power adapter for LED is 5V/4A

**Comment by aaronsutton** [comment]
I've basically given up on this ever working properly. My lights are powered at both ends from a 5V/2A supply and I've compiled the kernel myself with the proper patches for the STK1160, played with every setting I can think of, and the flicker is still awful. I suppose I could try shielding all the cables, but I'm not feeling hopeful.

**Comment by Poopi** [comment]
@gren2del Are you using the voltage translator? Please show the schematics...

**Comment by aaronsutton** [comment]
I thought the inverter chip was required for the WS2812 strips and not for the WS2801s. The circuit I'm using is attached. It should be noted that there is zero flickering when using hyperion to set a solid color. It only occurs when using the framegrabber.
![diagram](https://cloud.githubusercontent.com/assets/1634530/6830172/87b182ba-d2ee-11e4-8336-490465440b7d.png)

**Comment by Poopi** [comment]
According to the datasheet the ws2801 needs to be driven with minimum voltage of 0.8*VDD. SInce you pwered the LEDs from 5V this means that you need to drive them with minimum voltage of 4V but you can also powered them from 3.3V and then you don't need to have any level shifter.

**Comment by gren2del** [comment]
I am not. 
I use a similar wiring to aaronsutton. The difference is I connect only ground from LED to RPi as tge RPi is being powered through microUSB port. I power the LEDs according to the specs I got from the supplier. The LEDs are a 50 pcs. string. 
The power adapter is a 5V/4A one. I tried with a 3.5A from different manufacturer but to no success.

**Comment by bart015** [comment]
I had the same problem, but changing these 2 things in the v4l2 settings worked out for me;

"width" : 240,
"height" : 192,

**Comment by gren2del** [comment]
The possible reason why the random LED flickering occurs may be the LAN connection. I have tried to run some movies directly from sd card and through wifi usb adapter. I have not had any random flashes. I have read somewhere that the usb-ethernet adapter helps as well.

**Comment by leeroymeile** [comment]
I had the same problem. I fixed it with changing the data wires to the leds.

**Comment by tpmodding** [comment]
@evgsd can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
