### ISSUE TITLE
Hyperion 21:9 support

### ISSUE THREAD

**Issue by Casimir-Git** [tvdzwan/hyperion#269]
I want to figure out if this frame grabber is capable of grabbing the 21:9 aspect ratio to use. With or without HDMI duplicator.

**Comment by tvdzwan** [comment]
Could you give a little bit more details? The software-grabber just captures from a digital stream somewhere. It does not care about aspect ratio.
The usb-grabbers might. You should check this based on the chipset of the usb-grabber.

**Comment by Fid3lity** [comment]
USB grabber is one labeled VideoDVR, DC60 Y ordered on eBay. That's pretty
much all I know about it. Why I'm asking is because I was trying to use my
HDMI output on my GC to duplicate screen but it wouldn't go over 768p. That
made me wonder if the convertor is actually capable of grabbing this aspect
ratio.

**Comment by Fid3lity** [comment]
Do you by any chance know what might be up? Because I'm also fiddling around with an Arduino-based alternative which is not going that well :)

**Comment by tvdzwan** [comment]
The issue as you describe it is almost certainly related to your hardware components. One of your HDMI devices will not led you set the desired resolution. This will prompt the whole chain to bump back to 768p. It is hard to say whether it is the USB-grabber or the splitter or maybe both. If you have a second screen (with that resolution or maybe just 1080p) you could check that the splitter is capable of higher resolutions.
I myself do not own a splitter or grabber (or a 21:9 2560x1080 display :-( ), which gives me a disadvantage in solving issues with splitters or USB grabbers..

**Comment by Fid3lity** [comment]
It might have something to do with my main screen being connected to DP
instead of just a splitter output. And duplicating the screen to pick
something like 21:9 seems impossible. So I have not yet actually tested
with a splitter, but it wouldn't surprise me of that wouldn't solve the
issue. For now I'm looking at Arduino hoping that will be the fitting
extension in my case. And learn some of the programming on the go. Who
knows...

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
