### ISSUE TITLE
Failed to start hyperion.service: Unit hyperion.service failed to load: No such file or directory.

### ISSUE THREAD

**Issue by Saawber** [tvdzwan/hyperion#278]
Hi. Today, I´ve installed OSMC on my Raspberry PI 2, then I´ve installed hyperion in exact same order as is shown in tvdzwan installing guide. After "sudo sh ./install_hyperion.sh" it failed with this error:
Failed to start hyperion.service: Unit hyperion.service failed to load: No such file or directory. The whole installing log is below.. Any clues what to do?  
Also after "sudo apt-get install libqtcore4 libqtgui4 libqt4-network libusb-1.0-0 libprotobuf7 ca-certificates" PI sad that: E: Unable to locate package libprotobuf7

Thank you for you help

hyperion installation log:
Failed to stop hyperion.service: Unit hyperion.service not loaded.
Downloading hyperion
converted 'https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hype                                                                                                                                                             rion.tar.gz' (ANSI_X3.4-1968) -> 'https://raw.githubusercontent.com/tvdzwan/hype                                                                                                                                                             rion/master/deploy/hyperion.tar.gz' (UTF-8)
--2015-03-05 22:53:59--  https://raw.githubusercontent.com/tvdzwan/hyperion/mast                                                                                                                                                             er/deploy/hyperion.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.13                                                                                                                                                             3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7703220 (7.3M) [application/octet-stream]
Saving to: 'STDOUT'

-                   100%[=====================>]   7.35M  2.95MB/s   in 2.5s

2015-03-05 22:54:06 (2.95 MB/s) - written to stdout [7703220/7703220]

Installing startup script in init.d
insserv: warning: script 'hyperion' missing LSB tags and overrides
Failed to start hyperion.service: Unit hyperion.service failed to load: No such                                                                                                                                                              file or directory.

**Comment by r3dr4bbit** [comment]
Firstly, check where on your SDCard hyperion got installed to. By the look of things from the install script, it should be located under /opt/hyperion.

Secondly, check if the daemon is added correctly.  Not sure which one OSMC uses, but it is either /sbin/initctl or /usr/sbin/service.

I haven't work with OSMC yet, so please excuse met.

**Comment by Saawber** [comment]
Thank you for your reply. I´m not at home with my Pi right now, but I´ll check it after coming home today. But I tinkered in it yesterday, and as I saw, there was absolutely no hyperion folder under /opt, only VC or VS folder or something like that.. It kinda looks like hyperion installer didn´t created folder in propper directory. But to be sure, I´ll make clean instalation of OSMC and Hyperion today evening, and I´ll try to locate /hyperion folder and hyperion daemon again.

**Comment by r3dr4bbit** [comment]
Without looking too much into OSMC, I see it uses apt-get to obtain packages.  This tells me it is a bit more complex than OpenELEC, which I used.  Remember to installing Hyperion with the following (sudo is important):

sudo sh ./install_hyperion.sh

Also, I am a bit suspect of the following statement, which will probably be used in your case:

wget https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hyperion.tar.gz -O - | tar -C /opt -xz

If you script fails to install again, perform the following (untested code):
cd /opt
wget https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hyperion.tar.gz
tar -xzvf hyperion.tar.gz /opt
wget -N https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
sudo sh ./install_hyperion.sh

This will download and extract the archive manually, which you can verify.  It will then run the script, which should fail to extract, but since it was manually extracted should work. The remainder of the script should complete without errors. 

Please check back with results.

**Comment by Saawber** [comment]
Hi, thank you for you answer but it didn´t helped :(  I stopped at tar -xzvf hyperion.tar.gz /opt with this:

root@osmc:/opt# tar -xzvf hyperion.tar.gz /opt
tar: /opt: Not found in archive
tar: Exiting with failure status due to previous errors
root@osmc:/opt#

When I check opt folder via FileZilla, hyperion.tar.gz file is there :(

**Comment by r3dr4bbit** [comment]
Sorry, typo in my tar command: tar -xzvf hyperion.tar.gz -C /opt

It is normal for the config file to already be there, especially if the script was run once, or you placed it there.

For the two insserv warnings, please see: http://www.raspberrypi.org/forums/viewtopic.php?f=66&t=68263.  It boils down to an incomplete script.  I think the info block should be added to hide this error.

What I can deduct is that OSMC is using services.  This means that there should be a hyperion file in /etc/init.d.  Please confirm that.  It should be the same content as hyperion.tar.gz/init.d/hyperion.init.sh.  If it is not there, copy create a symbolic link, make it executable and then update rc.d

ln -fs /opt/hyperion/init.d/hyperion.init.sh /etc/init.d/hyperion
chmod +x /etc/init.d/hyperion
update-rc.d hyperion defaults 98 02

If you still don't have any success, please post your build number and I will attempt to duplicate the issue on my side.

**Comment by r3dr4bbit** [comment]
Also, please look at this page for OSMC. 

https://discourse.osmc.tv/t/rpi2-hyperion-osmc/449/9

**Comment by Saawber** [comment]
Thanks for your reply and help, but it didn´t work anyway :( hyperion file is in /etc/init.d folder after this:
ln -fs /opt/hyperion/init.d/hyperion.init.sh /etc/init.d/hyperion
 chmod +x /etc/init.d/hyperion
 update-rc.d hyperion defaults 98 02
but it is still refusing to work :( root@osmc:~# Failed to start hyperion.service: Unit hyperion.service failed to load: No such file or directory.
I used the Alpha4 and now I am on RC version, but no difference, still same problem :(

**Comment by ctugt** [comment]
Install Hyperion on OSMC
First we need to install some packages

sudo apt-get update && apt-get upgrade && apt-get install git libqtcore4 libqtgui4 libqt4-network libusb-1.0-0 libprotobuf9 ca-certificates

Download Hyperion:
wget -N https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh

This may fail when your systemtime is not correct! check time with:
date

Now install hyperion
sh ./install_hyperion.sh
put config in /etc

Enable GPIO's:
vi /boot/config.txt
add the next line
dtparam=spi=on

Now we need killall for some scripts im using
apt-get install psmisc

Now everytime it will run as root user when we boot, we dont want that otherwise we cannot use our colourswitch and on/off button
So we remove the hyperion symoblic link at /etc/init.d

Next we create hyperion.service file and put that in /etc/systemd/system (this wil open hyperion as OSMC user every boot)
[Unit]
Description=Hyperion
 
[Service]
Type=simple
User=osmc
Group=osmc
UMask=007
ExecStart=/opt/hyperion/bin/hyperiond /etc/hyperion.config.json
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
TimeoutStopSec=10
 
[Install]
WantedBy=multi-user.target

After that we copy the colourswitch.py, off.py and switch.py to /home/osmc/hyperion

Last we define the button in remote.xml 
<yellow>RunScript("/home/osmc/hyperion/colourswitch.py")</yellow>
<blue>RunScript("/home/osmc/hyperion/switch.py")</blue>
<red>RunScript("/home/osmc/hyperion/off.py")</red>
and put remote.xml on /home/osmc/.kodi/userdate/keymaps

Done!

**Comment by brindosch** [comment]
New install script will handle everything you need

closed
