### ISSUE TITLE
Lightstrip and HUE

### ISSUE THREAD

**Issue by webnar** [tvdzwan/hyperion#285]
Is it already possible to use a lightstrip and HUE at the same time.

**Comment by ntim** [comment]
Yes, the HUE api is universal for all lights you can connect to your bridge. Additionally, Hyperion will determine the device type from an identifier and the appropriate color space is set accordingly.

**Comment by webnar** [comment]
Thanks for the quick response. But how to configure it so that it works at the same time I can only give one device in the config. Now i have LEDstrip WS2801 but i want the HUE also.

**Comment by ntim** [comment]
A sorry, thought you mean the HUE lightstrips. Currently, multi device configuration is not possible but some users already asked for this feature. 

@tvdzwan: is this feature planned to be implemented?

**Comment by webnar** [comment]
Oke is it then possible to run multiple session of hyperion on same device that both listen to the same port?

**Comment by kleusch** [comment]
I have the HUE Lightstrips in Use and they are working good with hyperion.

But I have one question:

How can I disable my second HUE lamp? I have lightstrips and a LivingColor lamp and both of them are changing colors. When I only mention one LED in the config, it's always the first lamp (which is the LivingColor), that is reacting.

**Comment by ntim** [comment]
@kleusch 

This is possible by adding a "lightIds" json array with ids to the device section. Given you want to respond your first and third light you would add

    "lightIds":[1,3]

**Comment by ntim** [comment]
@webnar 

Maybe possible, don't know if the framegrabber is allowed to run twice or interferes with the other instance. Have you tried it?

**Comment by kleusch** [comment]
@ntim 

Perfect, this is working! Thanks.

I have one last question:
How can I increase the brightnes and the colors of the HUE lightstrip. Only with the two hsv values? If I set the value from 1.000 to 10.000 its obviously a little bit brighter, but i could be more. Is 10k the maximum?

**Comment by ntim** [comment]
I use the "xy" lights API attribute (CIE color space) to set a color and the "bri" to set the brightness. "hue" is also for the color ranging from 0 to 65535. Since "xy" is somewhat the "native" color setting for the HUE system I stick to that. Further information on the color space can be found here:

http://www.developers.meethue.com/documentation/color-conversions-rgb-xy

The "brighness" of a RGB color also be calculated during this conversion: It is simply given by "Y" from the intermediate result in the XYZ color space and ranging from 0 to 255. Thus the brightness of the HUE light should somehow reflect the brightness of the image. In fact I also hardly see brighness settings above 200 (I guess only white, etc.). Maybe there is some space for improvements left.

**Comment by joezorry** [comment]
Actually multi-device support would be awesome, have a Lightberry light strip and philips hue, would love to use both at the same time.

**Comment by Carote** [comment]
Yes, it would be awesome. 
Does anybody know if it will be possible ?

**Comment by ro8in** [comment]
I would also love to be able to use my leds and philips hue at the same time. Now i can't :(

**Comment by brindosch** [comment]
Stick with the new Proto/json forwader and a new hyperion instance

I will close this
