### ISSUE TITLE
Do I need to add a buffer?

### ISSUE THREAD

**Issue by tiny-e** [tvdzwan/hyperion#328]
I've got a pi2, a string of WS2801 pixel LED's, and a 5v, 8A power supply. Tried hooking up the LED strip to the GPIO header based on info from the hyperion github page and the pinout diagram from RaspberryPi.

The LED's barely light up, sometimes the first 3 are off, sometimes they are the only ones on, sometimes the string lights up to the end, sometimes a random number of LED's... always a reddish-amber color that I can't change via the command line or via the hyperCon java app.

Trying to figure out if I need a buffering circuit between the SPI interface and the LEDs, but I'm an electronics noob, and don't really have a frame of reference to work from / way to troubleshoot the string.
Based on reading I've done, it sounds like the SPI output is possibly too low a voltage for the WS2801 LED strip to deal with --but I'm not sure as the hyperion wiki mentions that people apparently are using them directly connected to the pi2..

Is anyone else having this issue, or can help me troubleshoot what's going on to make sure I'm not missing something easy?

LED's are these:  http://www.amazon.com/gp/product/B00KFJTS86/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1

**Comment by croaker-1** [comment]
It sounds like you are on the right track. Sometime the 3.3v from the RPi will happily drive a WS2801strip but it doesn't seem consistent. I currently use an Arduino Uno connected via USB to the RPi to drive my WS2801 strip. I have experimented with connecting them directly to my RPi...it worked but introduced an annoying flicker and inconsistent brightness. I've been thinking about building a buffer circuit but the Arduino setup works so well I haven't been in a rush to do it.

If you have access to an Arduino I recommend using it to test your strip and Hyperion setup. If it all works with the Arduino you can be almost certain that it's the 3.3v causing your problem.

Hope that helps.

**Comment by tiny-e** [comment]
I also noticed the other day that the WS2801 strip I ordered was a 12v strip… I tried using a 12v @ 1A power supply (to the strip only)…wonder if that’s enough.  I was able to see some things flash / flicker but with no rhyme or reason —other than it seemed to happen when I moved wires around.

I purchased a buffer board (https://www.futurlec.com/Mini_Opto_Isolator.shtml <https://www.futurlec.com/Mini_Opto_Isolator.shtml>) and tried to use that too — but I’m not sure at this point if anything really works as I have no known-good point to work from.  I also ordered a WS2810 stand alone controller from amazon, thinking I could test the strip with that.. maybe..

Thanks for the reply and please excuse my noobishness in the area of electronics… I can do the work / follow instructions, but I’m pretty new to things like this, and the terminology / some of the principles are a little daunting to me.

**Comment by croaker-1** [comment]
I did notice your strip was 12v which, at first, I thought was odd but it turns out I had just never looked for 12v WS2801 strips before. Adafruit does a strand of 12v WS2801 LEDs https://www.adafruit.com/products/683 and, although different than yours, should have the same basic requirements. Reading through the specs for both strips (yours and Adafruits) it seems your power supply may not be providing enough current at 1A. Adafruit estimates about 30mA/pixel at full white so your power supply is just able to drive 1m of your 5m strip at full brightness (assuming your LEDs draw a similar amount of power to Adafruits). You will probably have better luck with a 5-6A 12v supply which are fairly common for driving LED strips. Adafruit also has a tutorial on wiring their strip and controlling it with an Arduino https://learn.adafruit.com/36mm-led-pixels/pwiring which may give you some insight on your setup.

I can really appreciate how these stuff can appear so simple on the surface but become deceptively complex once you start trying to apply it. I still fall into that trap more often than I'd like...it's a constant learning curve (especially when it is only hobby and not a profession) but man I enjoy it (especially LEDs)! I'm still a relative noob myself (only been at this for a couple of years) so I'm hoping that, if I am mistaken about anything, any more experienced folks here will correct me.

**Comment by tiny-e** [comment]
I have an old computer psu that I use for desk-assembling 12v stuff ... Think I'll try that next.  I would imagine (but I don't know) that the controller still wants a 5v signal.(?). Does it matter If the 3v or 5v comes from the pi and the 12v comes from an unconnected source?

**Comment by croaker-1** [comment]
You are correct. The controller and the LED can have separate power sources as long as the grounds are tied together. Have a look at this image from the article I linked to earlier:

![led_pixels_arduinowiring12v](https://cloud.githubusercontent.com/assets/4653383/8741685/907fd724-2c54-11e5-9c9f-791e867844f0.png)

**Comment by brindosch** [comment]
Should be done

Closed
