### ISSUE TITLE
Hyperion forgets Lightpacks with Multi-Lightpack setup

### ISSUE THREAD

**Issue by Sp0rks** [tvdzwan/hyperion#354]
I have a three light pack setup that I would like to drive using a Pi with Hyperion but I am finding that every now and then Hyperion will not see one or two of the lightpacks when I have made changes to the config and had to restart the service with 'sudo service hyperion restart' (does it even with stop/start) and it will take a couple of reboots or a hard boot (unplug and re-plug the Pi) before all three are detected again

I am running firmware 7.6 on all three lightpack units

**Comment by pejotigrek** [comment]
I think I have similar problem.
I use two lightpack clones - and because of the length of the cables I had to connect the leds not with the ideal order.

Hyperion works "out of the box", turning on leds with no problem, but I need to reorder them. I tried to do that, but when I enter my "perfect configuration", leds won't work at all. what's up with that?

so, my questions/problems to solve:
1. can I reorder the leds? I mean if they will be numbered, what's the difference which part of the screen is assigned to each led? It looks like Hyperion MUST have everything in order, any change will cause fail at work.
2. can I address the lightpacks directly like the Boblight does? [configure two devices with serials, and then address the leds to particular device]? maybe that would do it?

**Comment by samcm** [comment]
I have the same problem as @Sp0rks. As well as Hyperion loading the lightpacks in an incorrect order, this seems to be somewhat resolvable after a couple reboots. 

Sp0rks did you find a solution?

**Comment by Sp0rks** [comment]
@samcm unfortunately I have no real solution to only having some of the lightpacks detected during a service restart. What I did find though is to restart the service over and over (sometimes as many as 8 times) until all are detected again. The order of the lightpack units is based on the serial number of the units (found that out digging around here somewhere, it isn't documented anywhere) which can be found on the box and the underside of the unit itself. The unit with the lowest serial number will be the first and the one with the highest will be last

@pejotigrek the lights themselves being in an incorrect order is an issue I had as well and after fiddling around for hours I found that physically changing the ports was the only solution. Although the lights were setup and plugged in, in correct order as per Prismatik and the Lightpack instructions I found Hyperion had its own idea of what order they should go in. 

Prismatik would go 1,2,3,4,5,6,7,8,9,10
Hyperion appeared to go 1,2,3,7,4,8,5,6,9,10 (example only, I can't remember the actual order now)

Changing the LED order in the config file has no real effect and was more hassle than it was worth for me. What I ended up doing was modifying the effects config for snake.json

Original:
{
	"name" : "Snake",
	"script" : "snake.py",
	"args" :
	{
		"rotation-time" : 10.0,
		"color" : [255, 0, 0],
		"percentage" : 25
	}
}

Modified (slow rotate, blue leds, no trail):
{
	"name" : "Snake",
	"script" : "snake.py",
	"args" :
	{
		"rotation-time" : 60.0,
		"color" : [0, 0, 255],
		"percentage" : 0
	}
}

and physically changed them as the lights were going around

**Comment by samcm** [comment]
@Sp0rks That's some really really useful information regarding the serials. I've sort of got it working now but it's still touch and go whenever the system gets restarted. Thanks mate!

**Comment by pejotigrek** [comment]
ok, after lots of tries, and few sheets of paper with drawn blinking patterns [my desktop is far away from the TV with leds ;(] I eventually got the right order of lights with my two lightpacks.

the only think that bothers me is lhat there's a 50/50 chance, that one of the lightpack is off after bootup.. all I need to do is:
1. manually stop and start hyperiond via SSH
2. reboot my pi
3. both 1&2

thanks god that pi boots with lightning speeds, but it's frustrating nonetheless..

**Comment by brindosch** [comment]
This should be done. Please ask the lightberry support for further specific questions

**Comment by WolfspiritM** [comment]
Hyperion still now and then starts with only one lightpack detected for me.
As a workaround for anyone having the same issue until Hyperion hopefully gets a way to tell it how many lightpacks it should wait for:

I changed the hyperion start script in /etc/initi.d/hyperion to log to /var/log/hyperion.log:
```
PID=`$DAEMON $DAEMONOPTS > /var/log/hyperion.log 2>&1 & echo $!`
````

I created a script (hyperiontest) that runs on every boot:
``` bash
#!/bin/bash
DONE=false

while [ "$done" != "true" ]
do
 RUNNING=$(pidof hyperiond | wc -w)
 if [ "$RUNNING" == "0" ]; then
  echo "not running"
  sleep 5
 fi
 sleep 5
 FOUND=`cat /var/log/hyperion.log|grep "2 Lightpack devices were found"`
 if [ "$FOUND" != "" ]; then
   DONE=true
 else
   /etc/init.d/hyperion restart
 fi
done
```
with the crontab:
```
@reboot /{PATHTOHYPERIONTESTSCRIPT}/hyperiontest &
``` 

So whenever my PI starts the script starts running and if the hyperion log does not show "2 Lightpack devices were found" it will restart hyperion and try again after 5 seconds...
Otherwise it will close.
So it doesn't fix the issue but at least I don't need to restart my pi over and over until it's fixed.
If you have more then 2 Lightpacks you might like to change the number in the "FOUND" line...

If you have one lightpack disconnected or if it's not available somehow this will also end up in an infinite loop with hyperion starting new every 5 seconds...

**Comment by penfold42** [comment]
Can you provide the log output from a successful startup and a startup where some are missing ?

**Comment by WolfspiritM** [comment]
Sure...here is a successful log:
http://pastebin.com/cMbmAebj

Here is a log where one fails to be detected:
http://pastebin.com/PNDVRxHi

I think the interesting part would be this:
`Unable to retrieve serial number(-9): LIBUSB_ERROR_PIPE`

After a few restarts of hyperiond both were detected again...but having another kind of error:
http://pastebin.com/YD6AZfjj (I sadly didn't check if they actually would work...I assume that they would)
`Unable to write 2 bytes to Lightpack device(-9): LIBUSB_ERROR_PIPE`

Then a few restarts later I even got none detected:
http://pastebin.com/SUAmhvs6

Then after another restart everything was fine again:
http://pastebin.com/DuG699cW

**Comment by redPanther** [comment]
the lightpack driver needs some extension. There is no good solution other than writing code. Currently multiple lightpacks are simply sorted by serial. This could be done better - e.g. serial numbers could be written in config in order the user want.
Another thing is, that the lightpack driver itself has no hot plug capability and no good error handling (e.g. if device with specified serial not found, wait until it connects).
On top of that we have currently 3+1 implementions for lightpack. 
This should be merged in one driver and of course multiple lightpacks should be integrated in that driver too.
.... in other words the lightpack support is currently a mess, imho. It shouldn't be hard to make a good driver, especially the difficult code is already written, but no active hyperion developer has a lightpack (and of course at least 2 of them needed to develop and test)

any help in that topic are welcome. BTW there is a lightpack driver that uses the hid api. This looks very promising. This driver exists as source in hyperion, but the code was never compiled in - so no one could ever test it. again, we need help here. (perhaps lightpack people want to help??)
