### ISSUE TITLE
Issue with latest OSMC, RPi 2 and Arduino Uno

### ISSUE THREAD

**Issue by Nico83500** [tvdzwan/hyperion#420]
Hi,
I have upgrade OSMC to the latest and now Hyperion doesn't work.
So I have do a clean install with latest version and same issue.
Before all was OK but now all is wrong.
Config :
- Raspberry Pi 2
- Arduino Uno USB
- LED WS2812B
- OSMC latest version
Thank you for your help !

**Comment by penfold42** [comment]
What errors do you get when you run Hyperion from the command line ?

**Comment by Nico83500** [comment]
I'm trying an other distri but I had these messages after Hyperion install on OSMC :
insserv: warning: script 'K01hyperion' missing LSB tags and overrides
insserv: warning: script 'hyperion' missing LSB tags and overrides

**Comment by Nico83500** [comment]
I've tried Raspbian Wheezy and Hyperion, no problem (kernel 3.18.11)
I've upgraded to Raspbian Jessie, without problem too (kernel 4.1.7). I'm going to try a clean install with Jessie.

**Comment by Nico83500** [comment]
Hyperion is OK with OpenElec 5.0.8 and 6.0.0

**Comment by Nico83500** [comment]
Ok so I don't know why but after a new clean install of OSMC now Hyperion works...
Sorry for wrong issue.

**Comment by kevinpanaro** [comment]
Hey @Nico83500, Can you give any details on your setup with this? I'm looking to do exactly what you've done with the exact same components and would love some direction.

**Comment by Nico83500** [comment]
Hi,
I'm using an SainSmart Uno (clone of Arduino Uno), a Raspberry Pi 2, 176 LEDs WS2812B and a 5V 10A power supply.
LEDs are connected to the SainSmart Uno, one wire for data, one wire for ground, one wire for +5V. LEDs are also connected to the 5V 10A power supply. SainSmart Uno is connected to Raspberry Pi 2 with USB. I've loaded a sketch into SainSmart Uno in order to drive LEDs.
I've also installed Hyperion to OSMC / OpenElec, create a configuration for Hyperion and all is working.

**Comment by kevinpanaro** [comment]
And using 'adalight' for the hyperion config i presume?
Can you still create your own effects, and control hyperion with the remote?

**Comment by penfold42** [comment]
I have done this - using adalight as the protocol with a small sketch on the arduino.
It worked well over USB but I had all sorts of problems trying this with the Pi's uart.

I then ditched it because I didn't want a USB port tied up and an external box.
I now have a bare atmega328 on some perf board plugged into the Pi and connected using the SPI bus. This looks to the Pi like a WS2801 but the code on the "arduino" listens to this and then sends talks to the WS2812 led strip.

Which ever approach you choose, it's all low level led drivers to all the effects, grabbing, Json interface, remote controls work the same.
