### ISSUE TITLE
Real leds colors

### ISSUE THREAD

**Issue by Trunxsnot** [tvdzwan/hyperion#426]
There's no real color correction tool working on hyperion.
For example, when i set (RGB):

White 255 255 255 FF FF FF it looks a little blue, 255 255 170 FF FF AA its a real white

Yellow 255 255 0 FF FF 00 it looks a little green, 255 170 0 FF AA 00 its a real yellow

I've tried all combinations of gamma, hsv, sat, thresthold, white and black and nothing works.

**Comment by penfold42** [comment]
What leds are you using ?

**Comment by Trunxsnot** [comment]
w2801

**Comment by AlexBGoode** [comment]
Just got an idea! Place into the project an Arduino and you may fix it as the following:
https://github.com/FastLED/FastLED/wiki/FastLED-Color-Correction

In my case the LED is WS2812B which doesn't work stable when connected directly to RPi 2 that's why I have to use Arduino in between. In your case WS2801 works well directly so consider to use Arduino as a proxy for color correction purposes

Cheers

**Comment by Sabcoll** [comment]
https://github.com/tvdzwan/hyperion/issues/405

**Comment by emc02** [comment]
There is no need to use an arduino if the LEDs are not stable. This is because the output voltage of the RPi is 3,3V and the WS2801 need 5V levels.
A simple level-shiter like IC 74HCT 08 can manage this and works fine for me, but this can't solve the problem with wrong colors. For me it also makes no sense to correct colors with another hardware device, because this could be done completely in software!

**Comment by penfold42** [comment]
Have you tested the LEDs directly ?

You should be able to just cat data directly to /dev/spi0.0

I wonder if they are faulty or if you have a weird power problem.

**Comment by AlexBGoode** [comment]
Good point regarding the voltage difference, **emc02**! Thanks
Looks like the root cause of the problem of direct connections...
However ironically any simple level shifters could cost for me more that a china arduino clone for 2$
I just googled for any 3.3v to 5v level shifter and fount offers around 3$
I agree that having the solution for color adjustments would be better without additional hardware, if we have such the solution in place now... meanwhile I am having fun with the powerful FastLED library which may do crazy things including r/g/b normalization and also white temperature adjustment btw

Thanks again for pointing out the voltage difference around GPIO!

**Comment by penfold42** [comment]
Any 74HCT series logic xhip will serve as a one way 3.3 to 5v level shifter.
$3.79 for 10pcs;
http://www.ebay.com.au/ulk/itm/250901587805

Make sure it's 74HCT and not 74HC

**Comment by emc02** [comment]
For example I am using port 3 of the level shifter to control a relays to switch the power supply of the LEDs on and off.
HCT is important, because the HC-Version needs 5V levels ;)
But that's all a little Off-Topic, because the main problem described here is the same that is here: https://github.com/tvdzwan/hyperion/issues/405

**Comment by AlexBGoode** [comment]
**emc02**, may I please ask you here once again? Smart people with cool ideas are so rare kind of internet assets 

I also had crazy ideas to control the power of LED via relays, and which process in your case send signals using port 3 of the level shifter? Do you somehow automate the detection of no data transmitted from hyperiond for a certain period of time? 

In my case I am trying to invent an approach when my arduino can identify the moment of idle and switch the relay off, then switch it back on in case of serial activities...

**Comment by emc02** [comment]
I made an Addon for OpenELEC (on RPi) to control Hyperion with JSON-RPC commands.
Infos can be found here: https://github.com/emc02/hyp-rpi-oelec-jsonrpc-remote-addon
It works well for me, but its still an experimental app.

**Comment by brindosch** [comment]
@emc02 
If you want to publish your addon, just create a wiki article to explain everything. I thought about where we could gather all these little nice progams.

Should be done
closed
