### ISSUE TITLE
Kodi Hardware acceleration RK3368 Support Android

### ISSUE THREAD

**Issue by homeruk187** [tvdzwan/hyperion#488]
Cant enable any hardware acceleration in KODI, LED's just blink. Once disabled (all) everything works fine. Do you have any updated XBMC clients that I can install. Thanks

**Comment by brindosch** [comment]
Could you please add some more information?
I am sure there is no special android support for hyperion with kodi 
But you could try this one
https://github.com/brindosch/script.service.hyperion

**Comment by homeruk187** [comment]
Thanks for the response and I'll try and explain my problem in more detail.

I am running with hyperion server from a pi connected to an Arduino Mega R3. I have a 4k android box with kodi running the hyperion client and everything works fine if I disable hardware acceleration in the video options in kodi. There are 3 hardware codecs I can chose from however the rockchip RK3368 codec for hardware acceleration when enabled causes the led just to flash. Some of the content I play needs the support of hardware in the video departments. )

**Comment by brindosch** [comment]
So you are using the Hyperion Kodi plugin. There are problems with devices that uses that hw blobs. I am sure there will never be a clean solution for this. Due to the point that rockchip have a very bad reputation (open source/documentation access) (in terms of software).

I am sorry. If someone find a solution, don´t hesitate to submit it.
/Closed
