### ISSUE TITLE
What is the max number of LEDs Hyperion can handle?

### ISSUE THREAD

**Issue by Samakisss** [tvdzwan/hyperion#494]
Hello there, how many LEDs maximum can Hyperion handle?

I had 116 ws2812b LEDs controlled by Arduino Uno with Adalight sketch on Ubuntu and it worked perfectly, although I decided to upgrade to 554 LEDs, re did the config file and the correct number of LEDs in the Adalight sketch but it won't work, I know someone has mentioned Arduino Uno memory capabilities but I all the FASTLed test through Arduino work perfctly, even decided to try with BobLight and works too, BobLight grab the video and output the lights. Although I like Hyperion better (iOS app) and would like to stick to it, so I can only conclude that the issue is Hyperion related as of how many LEDs can it handle?

Thank you.

**Comment by RickDB** [comment]
Uno indeed has the memory limit for that kind of setup (554 LEDs) and would advise an Mega 2560 as that gives you some headroom, recently did a 600 led setup here with APA102 ones which are completely driven by a rPi2:

http://forum.team-mediaportal.com/threads/diy-amblight-project-guide-hyperion-ws2801-ws2812b-apa102.128526/page-24#post-1174157

Hyperion handles that perfectly and also finished the config so will post a few new videos soon.

It all comes down to bandwidth and the rate the leds support without corrupting the data which in the case of WS2812B isn't that high due to its strict timings with no control over that whereas with WS2801 and APA102 you can control the SPI rate.

APA102 is the best choice for the smoothest experience in my opinion as you can push them pretty hard and have lots of leds p/m choices (30/60/72/144), once you reach a certain number of leds you might need to actually lower the SPI rate in the Hyperion config as you can get corruption over the line data (have them @ 8Mhz atm)
For Arduino with Adalight you need a pretty high baud rate between the rPi device with that many leds so not sure if that will work just as reliably.

Hope it helps and if you anymore questions just ask :)

**Comment by Samakisss** [comment]
Thanks for the reply and good to know that Hyperion can actually handle that amount of LEDs and I hear you about the LEDs susceptible to not handle it, although the 554 LEDs works perfctly fine when running FASTLed examples on Arduino so hopefully it is just an issue with the Uno and not the LEDs (getting my Arduino Mega today so we will see). 

I see people mentioning the RPi quite a lot when it comes to Ambilight so let me ask you that : do you use the RPi only to control your LEDs and have an HTPC (Ubuntu, Windows etc...) to play your movies or do you run EVERYTHING from the RPi (LEDs, Kodi via OpenELEC or OSMC)?

I have a dedicated HTPC running Ubuntu with Kodi installed, I watch 3D movies SBS or TAB, 1080p shows with DTS or DD audio and everything hooked to an AVR with 5.1 Home Theater. And then the Arduino is plugged to the computer to control the LEDs.

Running Kodi from RPi2 get very slow (from my experience) after customization (skins, 3D etc...) and not top for passthrough to the AVR.

But maybe the RPi2 is better than the Arduino Mega? Is it possible to somehow plug the RPi2 to my HTPC and let it manage the LEDs?

And yes regarding the power I am all set, 50A @ 5V.

Thanks for your reply, looking forward to your next.

**Comment by RickDB** [comment]
Have an dedicated rPi2 for Hyperion, AtmoLight sends images to the Hyperion Protoserver (same as with Kodi ).
Also have Hyperion live capture seup for gaming / stb etc.., AVR has 2 outs so the 2nd one goes to the live capture stick so that it works for all devices.
Downside with live capture is that you lose 24P (analog converters limit) so only use it for non-media playback.

HTPC is running Windows 10 with Mediaportal and the AtmoLight plugin, captures images straight off the DirectX buffer (fast and efficient).
Only tested Kodi under Windows a while back with an 218 led setup (WS2801 + Adalight) which worked but just not as smooth as with AtmoLight for some reason however the Hyperion plugin there might have improved since then.

RPi2 with SPI is easier and also less hops (and overhead) compared to Arduino with Adalight so that helps, no need for high baud rates or additional hardware.
It really depends on the led type on has on hand and if it's SPI than would definitely skip the Arduino and directly connect the leds.

**Comment by Samakisss** [comment]
Ok so if I follow you well you have your LEDs connected to a RPi2 (with RASPBMC or any other linux I presume?) running hyperion connected to the network (RJ45 or WiFi?) and have your Windows HTPC running AtmoLight "plugin" for the video capture, correct?

I had an almost similar setup (Windows 10 running Kodi with AmbiBox software, Arduino Uno with WS2812B and my RPi2 was used for NAS server) which is why I wanted to do a "cleaner" setup with my HTPC Ubuntu now being everything, it is my Media Player through Kodi, my NAS server (accessible through WAN) so the RPi2 is now extra and not necessary. 
I would feel silly to have a Linux server (my HTPC) that can run the Hyperion but still have to run another Linux on the RPi2 just for the LEDs, you know? 

I know very little about all these things you know and if Google wasn't part of our lives, I think I'd be worse....hehe. So maybe this would be a silly question but is the RPi2 the same type of device that the Arduino is or are they totally different type of devices?

**Comment by RickDB** [comment]
RPi2 indeed connected to RJ45 running Raspbian, Mediaportal with AtmoLight sends images to Hyperion over LAN and use the Hyperion live capture (V4L2) for everything non-media related.
Some run Hyperion on Linux servers but haven't experimented with that as the rPi is pretty cheap and low powered, agree that the less hardware the better though :)

No problem, you can see the RPi2 as an under powered PC device as the hardware it uses comes close to what your use in your phone for instance.
Arduino is a bit different, it has a microcontroller with no operation system and code runs straight of it which has its benefits mainly being fast / optimized and more suitable for some jobs as.
Mike from Adafruit has a great explanation here:

https://forums.adafruit.com/viewtopic.php?f=8&t=62583&p=317058#p317143

**Comment by Samakisss** [comment]
Man you are awesome, well, I will see tonight how that works out with the Arduino Mega and I will take a look at your hyperion config posted on your other post! I'll post then how it went! Thanks again!

**Comment by Samakisss** [comment]
GOOD NEWS! The Arduino Mega definitely fixed the issue, all my 554 LEDs are working now, very bright (maybe a bit too much lol) but just gotta work out on the tuning now. Gotta take a look at your config file RickDB, thanks for the tips! My next project is going to be setting up another ambilight, around my entertainment center ( if that is not too much) which involves running to hyperion daemon in the same time! Keeping posted and of course, any help would be much appreciated.

**Comment by RickDB** [comment]
Good to hear :+1: , can also post in the above Mediaportal Hyperion thread if you need any help :)

**Comment by tpmodding** [comment]
@Samakisss can be closed?

**Comment by Samakisss** [comment]
Yes sir! :)
