### ISSUE TITLE
The future of Hyperion

### ISSUE THREAD

**Issue by brindosch** [tvdzwan/hyperion#497]
This project is quite new, in july it reaches at least the 3th anniversary. Time goes by, projects raises and fails. And hyperion? People won´t stop to develop and commit new features and bugfixes.
There are thousands of people who loves this project! At least at youtube i got 4810 hits with selfmade ambilights driven by hyperion.

Maintainer are also just people. Changes in life are necessary and sometimes welcome, we all know this. So there is no blame for @tvdzwan and @poljvd. They wrote the main part of hyperion and we all are countless thankful for this!

The last months i saw some things that worry me a little bit

People start building their own versions of Hyper_Con and Hyperion and publish it. Don´t get me wrong, there is nothing wrong with it.
But this project is still alive because there are contributs. If people get the feeling, that this is a half abandoned project. What would the future bring?

A successful project like this needs maintainer. There are much things to do:

- Build new versions and check commits
- Update the Wiki according to the version and introducing new features
- Write a changelog that people could see what happend last
- Update HyperCon if new features are introduced (just to mention the newest: wisc blackborder improvement - no one will notice this)
- Managing the issue, answer them, close them and set labels for better overview
- and many more, at least hyperion should mediate a fair impression

This needs time, more time than one person could spend on a non-profit project like this.

I am not a big coder, but i could build images and do all other stuff until I digged in and know more about it (some fancy new features in my head)

I want to ask for people who are willing to spent some hours a week (or every two weeks) from their spare free time to keep that project remains what it is - fantastic

Yes, it is not my decision to add maintainer to hyperion and hypercon, but if we do nothing (ask), nothing will happen. I hope that @tvdzwan and @poljvd are willing and have the trust to do it. That we don´t scew up hyperion!

Every end is a new start!
Let us improve this project further!

Thank you for reading and your commitment

brindosch

PS. Sorry for my bad english grammar. I hope the try counts ;)
@Paulchen-Panther @ntim @wisc17 @kammerjaeger @Gamadril @NicoHood @bimsarck @frostworx and all others are invited.
PPS I am not reachable over the weekend

**Comment by pigbait** [comment]
I would love to help, but not sure how I can. I not a coder (i'm a google it, and try it out type) but if there anything i can do let me know.

**Comment by Gamadril** [comment]
Beeing a big fan of hyperion, I would be happy to help where I can. However there a several points that are IMHO problematic for any contributor here. And if I think about the incoming issues twice - as a maintainer I would give up long time ago.

hyperion started as a leightweight client running on RPi. Today it's a full blown binary which can grab from nearly everything and output on nearly everything and run on many systems. There are so many different platforms, linux distributions, output devices and grabbers, wishes coming every day from people, that nobody here can really test the code quality or even the functionality. You cannot even tell which version of hyperion you use, because there is no release versioning at all - would make no sense since on the core itself there were no significant changes.

You are right there is nothing wrong with own forks - I also created one (a branch actually) for my needs to get rid of QT and Python dependency and to use it with OpenWRT, but I don't plan to create a pull request for it - just because I don't know if it's working properly with all the devices out there in use and because I don't have time to do backports new commits/fixes from the main repo. Testing the builds and the installation script on each supported platform is not realistic for a single developer. I think most other "forks" have same problems. Looking at the issues list I can find only few things that might be interesting/useful for all hyperion users. Most of other problems and requests are based on exotic hardware configurations and infrastructure.

Regarding the future: I can imagine hyperion to become a pure "core" connecting all other stuff using loadable plugins/modules. All led devices, grabbers, remote connection servers, effect engine, image preprocessing, configuration loader - take them out and make hyperion lightweight again. That would also move the responsibility for each module to a known developer/team. This is a job for a good software architect to create a solid architecture and define clean interfaces. Sadly I have not much experience in that. I could help implementing, but not designing the software...

**Comment by ntim** [comment]
Totally agree with you. Maybe we should start sorting out the issues, which are platform and LED device specific, see what is left and important for a hyperion core. 

Regarding the plugin idea: within Qt there is an API for creating plugins and loading them at execution time: QtPlugin. May be it is applicable to hyperion but might also be rather complicated. Someone has to try.

**Comment by werkkrew** [comment]
I would love to help.  I built an Ambilight clone based on boblight many years ago and I was recently looking into updating some features and I came across Hyperion and I'm blown away.  Who can I get in touch with about contributing or helping in any way?  I have a pretty broad skill set and I would love to be a part of this.

**Comment by NicoHood** [comment]
Making it pluggable would be a very great idea.
We could base it on the current hyperion, but start a whole new project. We should decide on people who want to develop it and they should organize themselves to exchange with each other.

We could start a wiki page (here on hyperion) and write papers with ideas/concepts.
People who (really) want to help coding can enter there. And people who just have ideas (like me), could also add them. It should be meant as summary, not for discussion.

I think a new project would make sense. Or a more active fork where hyperion links to.
If he merged the PRs without checking them, we still can add links to new projects. But we should decide who wants to work on this, not that we end up in tons of forks again, because people disagree with each other.

For me personally I do not have time to help on the core. I might consider to port the fixes to the HID devices I made, when its ready. But I am spending ideas =)

**Comment by RickDB** [comment]
We reworked AtmoLight (Ambilight plugin) a while back with modular design for this exact same reason, it will bring flexibility and also gives you more consistent device handlers / targets as you can write several examples (net / serial etc..) for new developers without having them deal with core code or wrappers.
Project is in C# with very little C++ so the code doesn't apply here but if you guys needs some inspiration you can look here:

https://github.com/ambilight-4-mediaportal/AtmoLight/tree/master/AtmoLight.Core

**Comment by tociek** [comment]
I am also willing to help. I have developed [hyperion config plugin](https://github.com/LightberryEu/plugin.program.hyperion.configurator) for Kodi, so in case you see a need for any improvements in the plugin or you think that new plugin should be developed, I will be able to handle that in my free time,

**Comment by NicoHood** [comment]
So how is it going? I saw that @brindosch is now a Collaborator, so it seems you've talked with the guys who started the project? Any more infos how you all will continue to take over this project? About people, plans etc.

**Comment by brindosch** [comment]
@NicoHood you are fast ;)
I am glad that people are willing to help.
First, we have to clean up the issue tracker (note bugs/feature request and so on)

Also my new HyperCon version is ready with some often requested features!

My install script will be merged soon to prevent more faulty installs.

tpmodding is working on a whole new wiki.

Stay tuned! We need some time before we could move on.

**Thank you for all future contributes to Hyperion.** 
I am in contact with tvdzwan. All major decisions will be coordinated with him.

**Comment by pigbait** [comment]
can't wait to see what comes next.. thanks guys

**Comment by redPanther** [comment]
thx @brindosch  for taking care of hyperions future

If help needed with cmake, shell scripts, linux things and network stuff I can help.  
I'm "linux only" since 16 years and in my job I code for linux/bsd with c++/cmake/python/bash/qt.

BTW with github you can make a website. I think this could be very useful for connecting all the resources together and a website landing with nice pics and videos looks more professional then a github page.

For the future I wish we have tags so we can seriously think about distribution packages. This would make installation extreme easy and reliable.

**Comment by tpmodding** [comment]
Thx for website info redPanther :) i will look what we can do, but i'm new to github, only used to download projects. just give us a little time to update everything, we are working on it :)

**Comment by redPanther** [comment]
I think we can organize the code in a github "organization" atm hyperion is in @tvdzwan personal github area.
When we found a group/organization, then we can assign roles with specific rights. The Organization didn't belong to maintainers personal area. This is better to handle with multiple mantainers.

I already created a group so you can see how it looks like:
https://github.com/IluminationGroup

the organization can hold its repositories like hyperion, hypercon, ...

If interrested, drope a note I invite you to the IluminationGroup.

**Comment by brindosch** [comment]
Very interesting, i will discuss this with tvdzwan.
Thank you

**Comment by redPanther** [comment]
I also have a test organization where you can see how the website stuff works:

website: https://roboticsathome.github.io/
github page: https://github.com/roboticsAtHome

**Comment by brindosch** [comment]
organized like OpenHab :)
Thank you

**Comment by castaway1** [comment]
hello, im just a simple man using hyperion every day and enjoying watching movies with ambilight. Thank you for your hard work developers and peoples who contribute into this project. I wish long  life for hyperion as i cant imagine my life without it! keep it alive forever! :)
