### ISSUE TITLE
Pi 3 support ?

### ISSUE THREAD

**Issue by penfold42** [tvdzwan/hyperion#523]
Has anyone tested it yet ?

Hopefully mine will arrive tomorrow.

**Comment by ntim** [comment]
Mine will also arrive during the week. 

It runs in 32 bit mode for the foreseeable future and the video core is the same as in the previous model, so no I think we do not run into any problems.

**Comment by brindosch** [comment]
My install script may run into an "platform not detected error".
I also ordered one but not shipt yet.
I need the following output
`grep BCM* /proc/cpuinfo`
Thank you

**Comment by odious** [comment]
My Raspberry Pi 3 arrived yesterday and i can't get hyperion to work. I enabled SPI via raspi-config (the /boot/config.txt entry is there, the spi_bcm2835 kernel module is loaded), ran the install script and copied the config from my old Raspberry Pi 1, but my ws2801 LEDs don't light up.

The official [SPI doc](https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md) mentions that the Pi 3 uses a different SPI controller, could that be the problem?

**Comment by tpmodding** [comment]
mine didnt arrived today :( what is the output if you start it with command-line?

**Comment by odious** [comment]
http://pastebin.com/x3QCrctR seems fine, no errors or anything

**Comment by brindosch** [comment]
i wondered where you red @ the SPI page, that RPi3 has a changed spi ;)

**Comment by brindosch** [comment]
@penfold42 
Now it is confirmed, please close the issue
Thank you

**Comment by penfold42** [comment]
Not yet.

We also need to test ws2812

**Comment by rudelm** [comment]
@brindosch here's the output you've requested:
`grep BCM* /proc/cpuinfo
Hardware	: BCM2709`

@all
I've used the installer from the wiki and installation seems to be working so far. I've copied my hyperion.config.json from my raspberry pi 1 with ws2801 LEDs over to the config folder and I've enabled spi in the /flash/config.txt. Connection is the same as with the Raspberry Pi 1, although I've seen the new  pins (see this [link](https://pinout.xyz/)). I've also enabled remote access to kodi, so that the plugin can detect the current state. I can control the colors with the Hyperion remote iOS app. However, I have only around 50 of my 104 LEDs working, but at least they show the correct color. I'll keep you posted.

**Comment by brindosch** [comment]
@rudelm 
Thank you

**Comment by ntim** [comment]
Works out of the box on latest OSMC with Philips Hue.

**Comment by penfold42** [comment]
i finally upgraded to the pi3 over the weekend.

Works fine with my 2801 to 2812 protocol converter.

I'll close this for now given that native PWM 2812 support doesn't work on the pi2 so there's no point testing on the pi3

**Comment by minion9119** [comment]
Recruiter_MON

**Comment by brindosch** [comment]
@minion9119 
what du you want to say?
If you have issue, please open a new one. It is nor RPi3 related
