### ISSUE TITLE
Hyperion process dead on Raspberry Pi and ws2812b

### ISSUE THREAD

**Issue by StoneAgeSkillz** [tvdzwan/hyperion#540]
So, i've installed Hyperion on OSMC RPi 2. 
Hyperion status - running. 
Created config with HyperCon.jar, uploaded to RPi. 
Hyperion restart.
Hyperion status - running.
Altered to use with ws2812b, like many times before:

"device" :
{
    "name"       : "MyPi",
    "type"       : "ws2812b",
    "colorOrder" : "rgb"
},

Hyperion restart.
Hyperion status - proced dead:
osmc@osmc:~$ sudo /etc/init.d/hyperion status
Checking hyperiond...                             Process dead but pidfile exists

I think the dog is buried in this part. Something on that ws2812b part is wrong. And it causes OSMC to lag or crash. 

Any ideas? I'm not experienced on this linux stuff. Please tell me what to do to provide more info.

**Comment by brindosch** [comment]
We provide just support for RPi1 + PWM (leds) at the moment. A patch will be applied soon (see pull requests)
Users reported, that since osmc 11.2015 the support for pwm is broken.
Did you upgraded from a Pi1?

**Comment by StoneAgeSkillz** [comment]
Yes, i did, recently. You are right, on RPi 1 it worked until 2015-11 update, but because of that i'm still running 2015-10.
Does WS2812b + PWM work on OSMC 2015-10?

**Comment by tpmodding** [comment]
we will test all in a few hours :)

**Comment by snaked78** [comment]
Rpi B+ - Openelec (5.0.8-6.0.3) - ws2812b, according to instructions from wiki = is not working.
A couple of weeks ago, everything was fine

**Comment by brindosch** [comment]
You are using a RPi1?
You are welcome to test the fresh binarys :)
http://1drv.ms/22a6fk0

**Comment by snaked78** [comment]
@brindosch I use the first RPi. I can not run Hyperion. I use the new Hypercon to create a configuration file. Сonstantly one and the same problem - Unable to connect to host. 
What am I doing wrong?

**Comment by brindosch** [comment]
Thank you for feedback, i will compile new bins for testing now

**Comment by snaked78** [comment]
OSMC 2016.02-3 does not work. Installation is made from your script [#493](https://github.com/tvdzwan/hyperion/issues/493)
I have not much to thank. I'm just a user. But thank you for, then what you're doing all this work.

**Comment by brindosch** [comment]
Please insert the new hyperiond and check that the execution (x) is set.
Please don´t test at osmc at the moment, The script changes on osmc the user of hyperion to osmc/osmc, It is not possible to access the pwm pin!

[hyperiond.zip](https://github.com/tvdzwan/hyperion/files/170473/hyperiond.zip)

**Comment by snaked78** [comment]
@brindosch You are the best!!! Now everything works !!!

**Comment by kiryl85** [comment]
Hi @brindosch, I have RPi2 with OSMC and ws2812b leds so if you want to have something tested just please let me know and I will try do this as quickest as possible.

**Comment by StoneAgeSkillz** [comment]
As i wrote i'm not experienced at this linux stuff. But i learn fast. And i would like to help with testing.
If you provide some instructions, i'll do my best.

**Comment by Osmii** [comment]
Hi!
Today i installed Hyperion on Raspberry pi 3, with latest Osmc. I connected 50 Ws 1812b leds. Hyperion at that time worked fine. Then i generated config file with hypercon and then send it over sftp. Before that i maually corrected some parameters in config file as discripted in wiki. After that i couldnt start Hyperion no more. That status was returnd to me ;root@Medijskicenter:/home/osmc# sudo service hyperion start
root@Medijskicenter:/home/osmc# sudo service hyperion status
* hyperion.service - Hyperion Systemd service
   Loaded: loaded (/etc/systemd/system/hyperion.service; enabled)
   Active: failed (Result: start-limit) since Fri 2016-03-18 12:00:35 CET; 17s ago
  Process: 1680 ExecStart=/opt/hyperion/bin/hyperiond /etc/hyperion.config.json (code=killed, signal=SEGV)
 Main PID: 1680 (code=killed, signal=SEGV)

Mar 18 12:00:35 Medijskicenter hyperiond[1680]: "leds" : 49,
Mar 18 12:00:35 Medijskicenter hyperiond[1680]: "name" : "MyPi",
Mar 18 12:00:35 Medijskicenter hyperiond[1680]: "type" : "ws281x"
Mar 18 12:00:35 Medijskicenter hyperiond[1680]: }
Mar 18 12:00:35 Medijskicenter hyperiond[1680]: Can't open /dev/mem: Permission denied
Mar 18 12:00:35 Medijskicenter systemd[1]: hyperion.service: main process exited, code=killed, status=11/SEGV
Mar 18 12:00:35 Medijskicenter systemd[1]: Unit hyperion.service entered failed state.
Mar 18 12:00:35 Medijskicenter systemd[1]: hyperion.service start request repeated too quickly, refusing to start.
Mar 18 12:00:35 Medijskicenter systemd[1]: Failed to start Hyperion Systemd service.
Mar 18 12:00:35 Medijskicenter systemd[1]: Unit hyperion.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
root@Medijskicenter:/home/osmc#

Am i doing something wrong?

**Comment by StoneAgeSkillz** [comment]
As lon as i see it you are usin WS2812b, but config is not for them. Or is ws1812b right? And @brindosch wrote we should not test is on osmc, it's not posible to acces pwm pin. this is why it does not work.

**Comment by penfold42** [comment]
hyperiond[1680]: Can't open /dev/mem: Permission denied

What user account is Hyperion running as ?

**Comment by brindosch** [comment]
@Osmii 
the install script can´t handle the right settings for PWM leds. I will fix this on sunday during the bigger hyperion update and update the wiki accordingly too.

change the hyperion user from osmc to root
`nano /etc/systemd/system/hyperion.service`
`User=root`
`Group=root`
User reported, that on newer osmc versions >=11.2015 nothing works.
Could you report this?
and make sure you added `dtoverlay=pwm` to your config.txt and reboot

**Comment by Osmii** [comment]
Well, i changed hyperion user and group to root and it started to work :)
Im using Raspberry Pi 3, OSMC 02/2016 and 59 of Ws1812b leds. The leds are connected on GPIO 12!
Config in .jar file is;
                "name"       : "MyPi",
		"type"       : "ws281x",
		"colorOrder" : "grb",
		"leds"       : 59,
		"gpio"   	 : 12,
		"dmanum" 	 : 5,
		"freq"   	 : 800000
I didnt added  dtoverlay=pwm because i dont know in wich config.txt!
Also i noticed that sometimes hdmi drops connection(blank screen for a momment), maybe is related to hyperion?

**Comment by penfold42** [comment]
I've noticed the hdmi problem too.

After a reboot it happens, until I play a movie !

Do you see this too ?

**Comment by brindosch** [comment]
It is working with newer osmc? Because you changed the gpio port to 12 instead 18 right?
and you don´t need the dtoverlay? Now i am very confused. Because Openelec users added this to their config. And i have no positive report about osmc >=11.2015
Thank you very much. I don´t own PWM leds so my big hassle is i can´t test anything myself.

**Comment by penfold42** [comment]
Yes. Works mostly well.
Latest OSMC, rpi3, 281x driver.
Default gpio 18 and it doesn't matter if I have the PWM overlay or not.

I'll open a separate issue with more details, but:
- You MUST use hdmi - with composite, the LEDs  flicker like crazy.
- after a reboot, enabling Hyperion will cause the HDMI to cut in and out. After playing and stopping a video (or I suspect a screensaver) it works fine from then on.

Looks like some sort of low level hardware init problem.

**Comment by Osmii** [comment]
@penfold42 The problem with hdmi seems to be only when playing 1080 p movies, not with 720p or sd!
@brindosch  Yes, im using GPIO 12. Where do i set dtoverlay, i wana try to set it, to see if there is any diference?

**Comment by penfold42** [comment]
What are your framegrabber settings ?
A height of 16 or less causes this problem.

Have you tried stopping Hyperion, playing a movie and then starting Hyperion ?

**Comment by brindosch** [comment]
@Osmii 
`nano /boot/config.txt`
add `dtoverlay=pwm`

@penfold42 I found some information at the rpi overlay readme
```
Name:   pwm
Info:   Configures a single PWM channel
        Legal pin,function combinations for each channel:
          PWM0: 12,4(Alt0) 18,2(Alt5) 40,4(Alt0)            52,5(Alt1)
          PWM1: 13,4(Alt0) 19,2(Alt5) 41,4(Alt0) 45,4(Alt0) 53,5(Alt1)
        N.B.:
          1) Pin 18 is the only one available on all platforms, and
             it is the one used by the I2S audio interface.
             Pins 12 and 13 might be better choices on an A+, B+ or Pi2.
          2) The onboard analogue audio output uses both PWM channels.
          3) So be careful mixing audio and PWM.
          4) Currently the clock must have been enabled and configured
             by other means.
Load:   dtoverlay=pwm,<param>=<val>
Params: pin                     Output pin (default 18) - see table
        func                    Pin function (default 2 = Alt5) - see above
        clock                   PWM clock frequency (informational)
```

**Comment by penfold42** [comment]
Yes, the default for me on OSMC with nothing or with just "dtoverlay=pwm" is 18.

I had seen this previously, but the clock option gives me something to investigate as to why it only works with hdmi for me.

**Comment by Osmii** [comment]
@penfold42 My framegrabber value is 45, and there is no diffrerenc when starting stoping movie!
@brindosch No difference with dtoverlay.

**Comment by brindosch** [comment]
I am sure @penfold42 investigates this :)
But this may not be a fault of Hyperion the new ws281x driver is still new :)

**Comment by brindosch** [comment]
It seams we just could leave a warning (in case that) for osmc and PWM leds.
It is no issue that is hyperion related and we can´t get rid of the changes that where done by OSMC devs

/Closed
