### ISSUE TITLE
LED light oscillation

### ISSUE THREAD

**Issue by pete111** [tvdzwan/hyperion#61]
Hello, 
how can I prevent LED oscillation? Here is video what I mean http://www.youtube.com/watch?v=CryonJzwedI (best visible sec. 8-16)
It is especially visible when showing bright colors with less brightness.

**Comment by lobocobra** [comment]
sorry I was not specific enough.
Instead of using some regular cable between the LED Stripe and the Pi, I use a shielded cable, which was formerly an USB cable. You can also use a shielded Cat5/6 network cable for the connection.
By using such a cable you can eliminate the issues related to flickering (most likely).

What you should do is...
- 1) replace the cable to the LED Stripe with a shielded one (USB or cat5 network cable)
- 2) use power supply with enough ampere (5 or more)
- 3) connect pi and LED to same power supply
- 4) use an external usb hub with seperate power supply and add all you connect to PI only over this hub

Hope that helps
